project-include-y += include/
project-$(CONFIG_BUILD_AUX) += aux/
project-$(CONFIG_BUILD_CUST) += cust/
project-$(CONFIG_BUILD_DTB) += dtb/
project-$(CONFIG_BUILD_HOST) += host/
project-$(CONFIG_BUILD_LIB) += lib/
project-$(CONFIG_BUILD_MAIN) += main/
project-$(CONFIG_BUILD_NASM) += nasm/
