###
# scripts contains sources for various helper programs used throughout
# the kernel for the build process.
# ---------------------------------------------------------------------------
include top.mk
subdir-y	+= basic kconfig
